### ISSUE TITLE
Live example doesn't work

### ISSUE THREAD

**Issue by br3aking-bad** [brightcove/videojs-playlist-ui#17] opened 2016-04-06 19:33 UTC
Hello,

I have tried to use the live example but I always have the same errors : 

```
file:///C:/Users/1601067/Downloads/videojs-playlist-ui-master%20(1)/videojs-playlist-ui-master/node_modules/videojs-playlist/dist/global.js Failed to load resource: net::ERR_FILE_NOT_FOUND
example.html:56 Uncaught TypeError: player.playlist is not a function
```

I tried without success to find the global.js in the directories but nothing.

**Comment by gkatsev** [comment] 2016-04-06 19:50
Have you run `npm install` and `grunt build` before looking at the example?

**Comment by br3aking-bad** [comment] 2016-04-07 13:08
Ho yes, it work ! I am so sorry I am pretty new to this tool and I would never guess to type those commands. I have tried to do `npm install video.js  ` and `npm install videojs-playlist` and put it in the videojs-playlist-ui folder hahaha, anyway thank you :)

**Comment by gkatsev** [comment] 2016-04-07 15:41
No worries, we often just assume that people know this but we should probably make sure to update our README.

**Comment by akoutli** [comment] 2016-04-18 22:28
Where, when and how should we run the grunt build?

**Comment by gkatsev** [comment] 2016-04-18 22:35
the process is something along these lines:

```sh
$ git clone https://github.com/brightcove/videojs-playlist-ui.git
$ cd videojs-playlist-ui
$ npm install
$ grunt build
```
Afterwards, you can open up the example and it should work.

**Comment by akoutli** [comment] 2016-04-19 00:01
Thank you very much for the prompt reply.
Unfortunately, the example does ask for a "global.js" file, which I still cannot find... Maybe it is not needed for the example to run? In any case, it is not located anywhere in the video-playlist not the  video-playlist-ui folders, even after the npm and grunt commands.

**Comment by gkatsev** [comment] 2016-04-19 00:07
The only global file is coming from `videojs-playlist` which should've been installed locally when you ran `npm install`. I've just ran it locally in a new clone and it works fine.

**Comment by akoutli** [comment] 2016-04-19 00:25
Hm... I deleted the folders and repeated the whole process:
- git clone https://github.com/brightcove/videojs-playlist.git && cd videojs-playlist
- npm install
- npm run build (just in case)
- git clone https://github.com/brightcove/videojs-playlist-ui.git && cd videojs-playlist-ui
- npm install
- grunt build

I still not see the global.js in any fold in videojs-playlist. Do we need it for the playlist to work properly? I am asking, because I also want to include videojs-youtube (from your fork), so as to make a playlist which includes both youtube and user-uploaded videos.

**Comment by gkatsev** [comment] 2016-04-19 00:29
Ah, I see. videoj-playlist-ui currently expects videojs-playlist 1.x which *does* include the `global.js` in the dist folder in npm, that's what package.json says under dev dependencies.
The latest videojs-playlist doesn't build in the same way as the 1.x version, there's no global file there.

You do need videojs-playlist because that's what brings the playlist functionality, this plugin is just the UI piece. This means that you could substitute videojs-playlist with any other playlist plugin with the same API and videojs-playlist-ui will continue to work.

To use this repo with the 2.x version of videojs-playlist, just include the `dist/videojs-playlist.js` file

**Comment by akoutli** [comment] 2016-04-19 00:36
Oh dear... then we (or I :/ ) have a problem... You see, I had done those steps (installed and set up version 2 of videojs-playlist, videojs-playlist-ui and videojs-youtube) already and I could not get the Youtube videos to run properly in the playlist. Is that a known bug? 
I searched a lot, and I was hoping that maybe in the end it would be the missing global.js, but it appears not to be the case.

**Comment by gkatsev** [comment] 2016-04-19 00:38
it's possible that videojs-youtube is broken and doesn't work inside a playlist.
Can you open up another issue on videojs-playlist with a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.

**Comment by akoutli** [comment] 2016-04-19 00:41
Ok, I will - thank you very much for your help!

**Comment by Fyb3roptik** [comment] 2016-06-01 18:49
Can you please update the README with this info for us NEWBS???

**Comment by gkatsev** [comment] 2016-06-17 19:35
Btw, there's now an advanced live example with the playlist-ui on videojs.com: http://videojs.com/advanced/

**Comment by victor72** [comment] 2016-06-26 09:44
with the playlist-ui,  I can do the things as " the advanced live example" easily.

But I wonder how can I clear and initial the "vjs-playlist" OL ? 
 the things just as : 
now I have 2 playlist var player1 & player2

if the function can bring some parameters? such as :   player2.playlistUi("vjs-playlist") ?

**Comment by esuveyke** [comment] 2016-10-28 12:51
is the source to http://videojs.com/advanced/ available?

**Comment by gkatsev** [comment] 2016-10-28 16:02
Sure, it's up on the on the videojs.com repo: https://github.com/videojs/videojs.com/blob/master/_src-js/advanced.js and https://github.com/videojs/videojs.com/tree/master/_harp/advanced

**Comment by maxpaj** [comment] 2018-01-26 15:04
Maybe close this issue?

**Comment by gkatsev** [comment] 2018-01-26 15:35
I think that's reasonable.

**Closed by gkatsev** 2018-01-26 15:35 UTC
